import type { WordPair } from "./wordBank.types";

function p(word: string, easy: string, medium: string, hard: string, category: string): WordPair {
  return { word, clues: { easy, medium, hard }, category };
}


export const wordBank: WordPair[] = [
  p("Sushi", "raw", "rice", "seaweed", "Food"),
  p("Pizza", "cheese", "italian", "slice", "Food"),
  p("Tacos", "tortilla", "mexican", "filling", "Food"),
  p("Croissant", "buttery", "pastry", "flaky", "Food"),
  p("Ramen", "noodles", "broth", "steam", "Food"),
  p("Burrito", "beans", "wrapped", "foil", "Food"),
  p("Waffles", "breakfast", "grid", "syrup", "Food"),
  p("Dumpling", "steamed", "dough", "pleat", "Food"),
  p("Gelato", "creamy", "frozen", "scoop", "Food"),
  p("Pretzel", "salty", "twisted", "knot", "Food"),
  p("Lasagna", "layered", "pasta", "baked", "Food"),
  p("Brownie", "chocolate", "dessert", "square", "Food"),
  p("Bagel", "doughy", "breakfast", "hole", "Food"),
  p("Baguette", "crusty", "french", "loaf", "Food"),
  p("Baklava", "honey", "layers", "nuts", "Food"),
  p("Biryani", "spiced", "rice", "aromatic", "Food"),
  p("Bratwurst", "sausage", "grilled", "mustard", "Food"),
  p("Ceviche", "citrus", "seafood", "raw", "Food"),
  p("Cheesecake", "creamy", "dessert", "crust", "Food"),
  p("Churros", "fried", "cinnamon", "crispy", "Food"),
  p("Clam Chowder", "creamy", "seafood", "bowl", "Food"),
  p("Couscous", "grain", "north", "fluffy", "Food"),
  p("Crepe", "thin", "french", "folded", "Food"),
  p("Curry", "spiced", "sauce", "aromatic", "Food"),
  p("Donut", "fried", "sweet", "glazed", "Food"),
  p("Edamame", "soy", "steamed", "pods", "Food"),
  p("Falafel", "fried", "chickpea", "spiced", "Food"),
  p("Fish and Chips", "fried", "british", "battered", "Food"),
  p("Fondue", "melted", "cheese", "dipping", "Food"),
  p("French Fries", "fried", "potato", "crispy", "Food"),
  p("Gnocchi", "potato", "italian", "dumpling", "Food"),
  p("Goulash", "stew", "paprika", "hearty", "Food"),
  p("Gumbo", "stew", "creole", "okra", "Food"),
  p("Gyoza", "pan", "dumpling", "japanese", "Food"),
  p("Hummus", "chickpea", "spread", "mediterranean", "Food"),
  p("Ice Cream", "frozen", "sweet", "scoop", "Food"),
  p("Jambalaya", "rice", "creole", "spicy", "Food"),
  p("Kebab", "grilled", "skewer", "spiced", "Food"),
  p("Kimchi", "fermented", "korean", "spicy", "Food"),
  p("Lobster", "shellfish", "butter", "claws", "Food"),
  p("Macaron", "french", "almond", "delicate", "Food"),
  p("Mango", "tropical", "sweet", "juicy", "Food"),
  p("Miso Soup", "broth", "japanese", "umami", "Food"),
  p("Moussaka", "layered", "eggplant", "greek", "Food"),
  p("Nachos", "cheese", "chips", "toppings", "Food"),
  p("Omelette", "eggs", "folded", "breakfast", "Food"),
  p("Onion Rings", "fried", "crispy", "battered", "Food"),
  p("Pad Thai", "noodles", "peanuts", "stir", "Food"),
  p("Paella", "rice", "saffron", "spanish", "Food"),
  p("Pancakes", "fluffy", "breakfast", "stack", "Food"),
  p("Peking Duck", "crispy", "chinese", "glazed", "Food"),
  p("Pho", "broth", "vietnamese", "herbs", "Food"),
  p("Pierogi", "dumpling", "eastern", "filled", "Food"),
  p("Poke Bowl", "raw", "hawaiian", "bowl", "Food"),
  p("Popcorn", "popped", "snack", "buttery", "Food"),
  p("Poutine", "fries", "gravy", "cheese", "Food"),
  p("Quesadilla", "cheese", "tortilla", "melted", "Food"),
  p("Ratatouille", "vegetable", "french", "stewed", "Food"),
  p("Risotto", "creamy", "rice", "stirred", "Food"),
  p("Samosa", "fried", "spiced", "triangular", "Food"),
  p("Sashimi", "raw", "fish", "sliced", "Food"),
  p("Shawarma", "spit", "wrapped", "middle", "Food"),
  p("Spring Rolls", "crispy", "asian", "fried", "Food"),
  p("Steak", "grilled", "beef", "seared", "Food"),
  p("Sushi Roll", "rice", "seaweed", "rolled", "Food"),
  p("Tiramisu", "coffee", "italian", "layered", "Food"),
  p("Tom Yum", "soup", "thai", "sour", "Food"),
  p("Tzatziki", "yogurt", "cucumber", "greek", "Food"),
  p("Udon", "thick", "noodles", "japanese", "Food"),
  p("Vindaloo", "curry", "goan", "spicy", "Food"),
  p("Yorkshire Pudding", "baked", "british", "puffy", "Food"),
  p("Eiffel Tower", "paris", "iron", "lattice", "Places"),
  p("Grand Canyon", "arizona", "gorge", "erosion", "Places"),
  p("Times Square", "neon", "crowded", "billboard", "Places"),
  p("Sahara Desert", "sand", "arid", "dunes", "Places"),
  p("Great Wall", "china", "long", "brick", "Places"),
  p("Amazon Rainforest", "jungle", "rainforest", "canopy", "Places"),
  p("Mount Everest", "tall", "summit", "altitude", "Places"),
  p("Venice", "canals", "gondola", "lagoon", "Places"),
  p("Colosseum", "rome", "arena", "arches", "Places"),
  p("Niagara Falls", "waterfall", "mist", "plunge", "Places"),
  p("Acropolis", "athens", "ancient", "marble", "Places"),
  p("Alhambra", "moorish", "spain", "palace", "Places"),
  p("Angkor Wat", "temple", "cambodia", "ruins", "Places"),
  p("Big Ben", "london", "clock", "gothic", "Places"),
  p("Blue Lagoon", "iceland", "geothermal", "milky", "Places"),
  p("Buckingham Palace", "london", "royal", "guards", "Places"),
  p("Burj Khalifa", "dubai", "tallest", "spire", "Places"),
  p("Chichen Itza", "pyramid", "maya", "yucatan", "Places"),
  p("Christ the Redeemer", "rio", "statue", "outstretched", "Places"),
  p("Dead Sea", "salty", "float", "lowest", "Places"),
  p("Easter Island", "moai", "remote", "statues", "Places"),
  p("Edinburgh Castle", "scotland", "cliff", "fortress", "Places"),
  p("Forbidden City", "beijing", "imperial", "courtyards", "Places"),
  p("Galapagos Islands", "wildlife", "remote", "turtles", "Places"),
  p("Golden Gate Bridge", "san", "suspension", "orange", "Places"),
  p("Great Barrier Reef", "coral", "australia", "diving", "Places"),
  p("Hagia Sophia", "istanbul", "dome", "byzantine", "Places"),
  p("Hollywood Sign", "los", "hills", "letters", "Places"),
  p("Iguazu Falls", "waterfalls", "border", "mist", "Places"),
  p("Louvre", "paris", "museum", "glass", "Places"),
  p("Machu Picchu", "inca", "mountain", "ruins", "Places"),
  p("Marina Bay Sands", "singapore", "rooftop", "infinity", "Places"),
  p("Mont Saint-Michel", "tidal", "france", "abbey", "Places"),
  p("Mount Fuji", "volcano", "japan", "snow", "Places"),
  p("Neuschwanstein Castle", "bavaria", "fairytale", "turrets", "Places"),
  p("Petra", "jordan", "carved", "rose", "Places"),
  p("Pyramids of Giza", "egypt", "pharaoh", "limestone", "Places"),
  p("Red Square", "moscow", "kremlin", "cobbles", "Places"),
  p("Sagrada Familia", "gaudi", "barcelona", "spires", "Places"),
  p("Santorini", "greece", "caldera", "whitewash", "Places"),
  p("Statue of Liberty", "harbor", "copper", "torch", "Places"),
  p("Stonehenge", "stones", "neolithic", "alignment", "Places"),
  p("Sydney Opera House", "sails", "harbor", "concrete", "Places"),
  p("Taj Mahal", "marble", "india", "mausoleum", "Places"),
  p("Tower Bridge", "london", "bascule", "thames", "Places"),
  p("Uluru", "monolith", "australia", "sandstone", "Places"),
  p("Versailles", "palace", "france", "gardens", "Places"),
  p("Yellowstone", "geyser", "park", "bison", "Places"),
  p("Zion National Park", "canyon", "utah", "sandstone", "Places"),
  p("Guitar", "strings", "wood", "fret", "Objects"),
  p("Telescope", "stars", "lenses", "tripod", "Objects"),
  p("Skateboard", "wheels", "deck", "grind", "Objects"),
  p("Chandelier", "ceiling", "crystal", "pendant", "Objects"),
  p("Typewriter", "keys", "vintage", "ribbon", "Objects"),
  p("Compass", "north", "magnetic", "bearing", "Objects"),
  p("Hourglass", "sand", "timer", "grains", "Objects"),
  p("Trampoline", "bounce", "springs", "rebound", "Objects"),
  p("Binoculars", "lenses", "zoom", "optics", "Objects"),
  p("Lava Lamp", "lava", "groovy", "wax", "Objects"),
  p("Accordion", "bellows", "keys", "squeeze", "Objects"),
  p("Backpack", "straps", "zipper", "carry", "Objects"),
  p("Barometer", "pressure", "weather", "mercury", "Objects"),
  p("Basketball", "orange", "bouncy", "dimpled", "Objects"),
  p("Blender", "smoothie", "blades", "pitcher", "Objects"),
  p("Boomerang", "curved", "throw", "return", "Objects"),
  p("Calculator", "buttons", "math", "lcd", "Objects"),
  p("Camera", "lens", "shutter", "flash", "Objects"),
  p("Candle", "wick", "wax", "flame", "Objects"),
  p("Clipboard", "clamp", "paper", "flat", "Objects"),
  p("Drone", "propellers", "remote", "hover", "Objects"),
  p("Flashlight", "beam", "battery", "tube", "Objects"),
  p("Globe", "sphere", "continents", "spin", "Objects"),
  p("Hammock", "fabric", "ropes", "swing", "Objects"),
  p("Headphones", "ears", "audio", "cushion", "Objects"),
  p("Joystick", "gaming", "stick", "buttons", "Objects"),
  p("Kaleidoscope", "colors", "tube", "mirrors", "Objects"),
  p("Lantern", "light", "glass", "handle", "Objects"),
  p("Magnifying Glass", "lens", "enlarge", "handle", "Objects"),
  p("Metronome", "tick", "tempo", "pendulum", "Objects"),
  p("Microscope", "slides", "tiny", "lenses", "Objects"),
  p("Parachute", "canopy", "sky", "cords", "Objects"),
  p("Piano", "keys", "pedals", "soundboard", "Objects"),
  p("Pinwheel", "spin", "wind", "paper", "Objects"),
  p("Projector", "beam", "screen", "lamp", "Objects"),
  p("Rubiks Cube", "twist", "colors", "puzzle", "Objects"),
  p("Scissors", "blades", "cut", "hinge", "Objects"),
  p("Segway", "wheels", "balance", "electric", "Objects"),
  p("Snow Globe", "shaker", "glitter", "dome", "Objects"),
  p("Stethoscope", "doctor", "chest", "tubing", "Objects"),
  p("Sundial", "shadow", "time", "gnomon", "Objects"),
  p("Thermometer", "temperature", "mercury", "scale", "Objects"),
  p("Treadmill", "running", "belt", "gym", "Objects"),
  p("Ukulele", "small", "strings", "hawaiian", "Objects"),
  p("Violin", "bow", "strings", "chin", "Objects"),
  p("Windmill", "blades", "wind", "grind", "Objects"),
  p("Xylophone", "bars", "mallets", "wood", "Objects"),
  p("Yo-Yo", "string", "spin", "toy", "Objects"),
  p("Zipper", "teeth", "slide", "fastener", "Objects"),
  p("Surfing", "waves", "ocean", "board", "Activities"),
  p("Karaoke", "singing", "mic", "lyrics", "Activities"),
  p("Rock Climbing", "rock", "ropes", "crux", "Activities"),
  p("Yoga", "stretch", "poses", "breath", "Activities"),
  p("Scuba Diving", "underwater", "tanks", "buoyancy", "Activities"),
  p("Archery", "arrows", "target", "draw", "Activities"),
  p("Snowboarding", "snow", "slope", "carve", "Activities"),
  p("Pottery", "clay", "wheel", "kiln", "Activities"),
  p("Skydiving", "parachute", "freefall", "canopy", "Activities"),
  p("Fencing", "swords", "foil", "parry", "Activities"),
  p("Badminton", "shuttlecock", "net", "racket", "Activities"),
  p("Baseball", "bat", "diamond", "pitch", "Activities"),
  p("Billiards", "cue", "balls", "felt", "Activities"),
  p("Bowling", "pins", "lane", "strike", "Activities"),
  p("Camping", "tent", "fire", "outdoors", "Activities"),
  p("Cheerleading", "pom", "stunt", "routine", "Activities"),
  p("Chess", "board", "strategy", "checkmate", "Activities"),
  p("Cycling", "bike", "pedals", "helmet", "Activities"),
  p("Dancing", "rhythm", "steps", "music", "Activities"),
  p("Fishing", "rod", "bait", "reel", "Activities"),
  p("Golf", "swing", "fairway", "putt", "Activities"),
  p("Hiking", "trail", "boots", "summit", "Activities"),
  p("Horseback Riding", "saddle", "reins", "gallop", "Activities"),
  p("Ice Skating", "blades", "rink", "glide", "Activities"),
  p("Juggling", "balls", "catch", "rhythm", "Activities"),
  p("Karate", "belt", "dojo", "kick", "Activities"),
  p("Knitting", "yarn", "needles", "stitch", "Activities"),
  p("Meditation", "still", "breath", "mindful", "Activities"),
  p("Paintball", "mask", "splat", "cover", "Activities"),
  p("Paragliding", "canopy", "ridge", "thermal", "Activities"),
  p("Ping Pong", "paddle", "table", "spin", "Activities"),
  p("Rollerblading", "wheels", "pavement", "stride", "Activities"),
  p("Rowing", "oars", "boat", "stroke", "Activities"),
  p("Sailing", "mast", "wind", "helm", "Activities"),
  p("Skateboarding", "ollie", "ramp", "deck", "Activities"),
  p("Skiing", "slopes", "poles", "powder", "Activities"),
  p("Snorkeling", "mask", "reef", "fins", "Activities"),
  p("Swimming", "pool", "strokes", "laps", "Activities"),
  p("Table Tennis", "paddle", "net", "rally", "Activities"),
  p("Tennis", "racket", "court", "serve", "Activities"),
  p("Volleyball", "net", "spike", "beach", "Activities"),
  p("Water Polo", "pool", "ball", "tread", "Activities"),
  p("Weightlifting", "barbell", "gym", "rep", "Activities"),
  p("Wrestling", "mat", "pin", "grapple", "Activities"),
  p("Penguin", "waddle", "antarctic", "tuxedo", "Animals"),
  p("Chameleon", "color", "lizard", "camouflage", "Animals"),
  p("Octopus", "eight", "tentacles", "ink", "Animals"),
  p("Flamingo", "pink", "legs", "filter", "Animals"),
  p("Platypus", "duckbill", "odd", "mammal", "Animals"),
  p("Jellyfish", "sting", "gelatin", "pulse", "Animals"),
  p("Peacock", "feathers", "fan", "iridescent", "Animals"),
  p("Armadillo", "armor", "texas", "roll", "Animals"),
  p("Narwhal", "tusk", "arctic", "spiral", "Animals"),
  p("Axolotl", "salamander", "gills", "regeneration", "Animals"),
  p("Aardvark", "ant", "snout", "nocturnal", "Animals"),
  p("Albatross", "wingspan", "ocean", "glide", "Animals"),
  p("Alligator", "swamp", "jaws", "reptile", "Animals"),
  p("Alpaca", "fluffy", "andes", "spit", "Animals"),
  p("Antelope", "savanna", "horns", "swift", "Animals"),
  p("Baboon", "primate", "muzzle", "troops", "Animals"),
  p("Badger", "burrow", "stripe", "fierce", "Animals"),
  p("Barracuda", "teeth", "reef", "fast", "Animals"),
  p("Beaver", "dam", "teeth", "tail", "Animals"),
  p("Bison", "plains", "herd", "shaggy", "Animals"),
  p("Blue Whale", "largest", "ocean", "blowhole", "Animals"),
  p("Capybara", "rodent", "semi", "chill", "Animals"),
  p("Cheetah", "fastest", "spots", "sprint", "Animals"),
  p("Cobra", "hood", "venom", "strike", "Animals"),
  p("Coyote", "howl", "desert", "clever", "Animals"),
  p("Crab", "claws", "sideways", "shell", "Animals"),
  p("Dolphin", "smart", "pod", "click", "Animals"),
  p("Eagle", "talon", "soar", "prey", "Animals"),
  p("Elephant", "trunk", "tusks", "herd", "Animals"),
  p("Emu", "flightless", "australia", "stride", "Animals"),
  p("Fennec Fox", "ears", "desert", "tiny", "Animals"),
  p("Giraffe", "neck", "spots", "tall", "Animals"),
  p("Gorilla", "silverback", "knuckle", "strong", "Animals"),
  p("Hedgehog", "spines", "curl", "nocturnal", "Animals"),
  p("Hippopotamus", "river", "massive", "yawn", "Animals"),
  p("Hummingbird", "tiny", "hover", "iridescent", "Animals"),
  p("Hyena", "laugh", "scavenger", "clan", "Animals"),
  p("Iguana", "lizard", "spines", "bask", "Animals"),
  p("Jaguar", "rosettes", "jungle", "stalk", "Animals"),
  p("Kangaroo", "pouch", "hop", "outback", "Animals"),
  p("Koala", "eucalyptus", "sleepy", "marsupial", "Animals"),
  p("Komodo Dragon", "lizard", "island", "venom", "Animals"),
  p("Lemur", "ring", "madagascar", "leap", "Animals"),
  p("Leopard", "spots", "tree", "stealth", "Animals"),
  p("Llama", "andes", "spit", "wool", "Animals"),
  p("Manatee", "gentle", "seagrass", "slow", "Animals"),
  p("Meerkat", "sentinel", "desert", "stand", "Animals"),
  p("Moose", "antlers", "boreal", "wade", "Animals"),
  p("Orca", "blackfish", "pod", "dorsal", "Animals"),
  p("Ostrich", "fast", "egg", "flightless", "Animals"),
  p("Otter", "playful", "river", "whisker", "Animals"),
  p("Owl", "nocturnal", "silent", "talon", "Animals"),
  p("Panda", "bamboo", "black", "cuddly", "Animals"),
  p("Panther", "black", "stalk", "jungle", "Animals"),
  p("Porcupine", "quills", "nocturnal", "climb", "Animals"),
  p("Raccoon", "mask", "trash", "dexterous", "Animals"),
  p("Red Panda", "cute", "bamboo", "fluffy", "Animals"),
  p("Rhinoceros", "horn", "charge", "thick", "Animals"),
  p("Sea Turtle", "shell", "ocean", "migrate", "Animals"),
  p("Seahorse", "curly", "male", "camouflage", "Animals"),
  p("Sloth", "slow", "hanging", "algae", "Animals"),
  p("Snow Leopard", "mountain", "spots", "tail", "Animals"),
  p("Tapir", "snout", "jungle", "odd", "Animals"),
  p("Toucan", "beak", "rainforest", "colorful", "Animals"),
  p("Walrus", "tusks", "arctic", "whisker", "Animals"),
  p("Warthog", "tusks", "savanna", "wallow", "Animals"),
  p("Wolverine", "fierce", "snow", "scavenger", "Animals"),
  p("Zebra", "stripes", "herd", "savanna", "Animals"),
  p("Aurora", "lights", "polar", "ionized", "Nature"),
  p("Earthquake", "seismic", "fault", "tremor", "Nature"),
  p("Hurricane", "cyclone", "wind", "eye", "Nature"),
  p("Lightning", "bolt", "storm", "flash", "Nature"),
  p("Rainbow", "prism", "arc", "spectrum", "Nature"),
  p("Tsunami", "wave", "ocean", "shore", "Nature"),
  p("Volcano", "lava", "erupt", "magma", "Nature"),
  p("Waterfall", "cascade", "cliff", "mist", "Nature"),
  p("Black Hole", "gravity", "infinite", "event", "Science"),
  p("DNA", "helix", "genes", "strand", "Science"),
  p("Gravity", "pull", "mass", "orbit", "Science"),
  p("Microscope Slide", "glass", "specimen", "thin", "Science"),
  p("Periodic Table", "elements", "chemistry", "atomic", "Science"),
  p("Photosynthesis", "chlorophyll", "sun", "glucose", "Science"),
  p("Solar System", "planets", "orbit", "sun", "Science"),
  p("Telescope Array", "radio", "dish", "signals", "Science"),
  p("Vaccine", "immunity", "needle", "antigen", "Science"),
  p("Superhero", "cape", "powers", "mask", "Culture"),
  p("Time Travel", "paradox", "future", "machine", "Culture"),
  p("Zombie", "undead", "horde", "brains", "Culture"),
  p("Pirate", "ship", "treasure", "parrot", "Culture"),
  p("Wizard", "spell", "wand", "robe", "Culture"),
  p("Detective", "clue", "magnifying", "case", "Culture"),
  p("Circus", "tent", "acrobat", "clown", "Culture"),
  p("Broadway", "theater", "musical", "stage", "Culture"),
  p("Video Game", "controller", "pixels", "level", "Culture"),
  p("Podcast", "audio", "episode", "mic", "Culture"),
  p("Marathon", "26", "running", "finish", "Sports"),
  p("Triathlon", "swim", "bike", "run", "Sports"),
  p("Cricket", "bat", "wicket", "pitch", "Sports"),
  p("Rugby", "scrum", "oval", "tackle", "Sports"),
  p("Soccer", "goal", "pitch", "cleats", "Sports"),
  p("Hockey", "puck", "ice", "stick", "Sports"),
  p("Lacrosse", "net", "stick", "field", "Sports"),
  p("Boxing", "ring", "gloves", "knockout", "Sports"),
  p("Gymnastics", "beam", "flip", "vault", "Sports"),
  p("Sumo Wrestling", "dohyō", "heavy", "shiko", "Sports"),
  p("Discus Throw", "spin", "ring", "release", "Sports"),
  p("Bamboo", "hollow", "fast", "pandas", "Plants"),
  p("Cactus", "spines", "desert", "succulent", "Plants"),
  p("Cherry Blossom", "pink", "spring", "petals", "Plants"),
  p("Dandelion", "puff", "weed", "seeds", "Plants"),
  p("Fern", "fronds", "shade", "spores", "Plants"),
  p("Mangrove", "roots", "coast", "brackish", "Plants"),
  p("Oak Tree", "acorn", "sturdy", "shade", "Plants"),
  p("Orchid", "exotic", "epiphyte", "delicate", "Plants"),
  p("Palm Tree", "fronds", "tropical", "coconut", "Plants"),
  p("Rose", "thorns", "perfume", "stem", "Plants"),
  p("Sunflower", "tall", "seeds", "yellow", "Plants"),
  p("Venus Flytrap", "snap", "carnivorous", "bog", "Plants"),
  p("Willow", "weeping", "flexible", "riverbank", "Plants"),
  p("Smartphone", "touchscreen", "apps", "pocket", "Technology"),
  p("Laptop", "keyboard", "portable", "hinge", "Technology"),
  p("Router", "wifi", "blinking", "bandwidth", "Technology"),
  p("Satellite", "orbit", "signal", "dish", "Technology"),
  p("Blockchain", "ledger", "crypto", "immutable", "Technology"),
  p("Firewall", "security", "packets", "rules", "Technology"),
  p("USB Drive", "flash", "portable", "stick", "Technology"),
  p("Bluetooth", "wireless", "pairing", "short", "Technology"),
  p("QR Code", "square", "scan", "matrix", "Technology"),
  p("3D Printer", "layer", "filament", "additive", "Technology"),
  p("Tuxedo", "formal", "bowtie", "lapel", "Fashion"),
  p("Sneakers", "laces", "sole", "casual", "Fashion"),
  p("Sombrero", "wide", "mexican", "shade", "Fashion"),
  p("Kimono", "sash", "japanese", "wrap", "Fashion"),
  p("Crown", "jewels", "royal", "head", "Fashion"),
  p("Leather Jacket", "zipper", "rebel", "collar", "Fashion"),
  p("Flip Flops", "rubber", "beach", "thong", "Fashion"),
  p("Beret", "french", "tilted", "wool", "Fashion"),
  p("Mittens", "winter", "thumb", "pair", "Fashion"),
  p("Corset", "laced", "tight", "waist", "Fashion"),
  p("Bookshelf", "shelves", "spine", "wood", "Home"),
  p("Grandfather Clock", "pendulum", "chime", "tall", "Home"),
  p("Hammock Chair", "swing", "indoor", "cocoon", "Home"),
  p("Kitchen Island", "counter", "stools", "prep", "Home"),
  p("Recliner", "footrest", "lever", "lounge", "Home"),
  p("Vanity", "mirror", "drawers", "makeup", "Home"),
  p("Wine Rack", "bottles", "cork", "storage", "Home"),
  p("Beanbag", "foam", "floor", "slouch", "Home"),
  p("Coat Rack", "hooks", "entryway", "hats", "Home"),
  p("Nightstand", "lamp", "bedside", "drawer", "Home"),
  p("Saxophone", "reed", "brass", "jazz", "Music"),
  p("Harmonica", "blues", "blow", "pocket", "Music"),
  p("Tambourine", "jingles", "shake", "frame", "Music"),
  p("Maracas", "latin", "rhythm", "gourd", "Music"),
  p("Cello", "bow", "deep", "endpin", "Music"),
  p("Trumpet", "valves", "brass", "mute", "Music"),
  p("Drum Kit", "cymbals", "sticks", "throne", "Music"),
  p("Turntable", "vinyl", "needle", "scratch", "Music"),
  p("Kazoo", "hum", "buzz", "membrane", "Music"),
  p("Bagpipes", "scotland", "drone", "reed", "Music"),
  p("Architect", "blueprint", "design", "scale", "Jobs"),
  p("Barista", "espresso", "latte", "steam", "Jobs"),
  p("Blacksmith", "forge", "anvil", "hammer", "Jobs"),
  p("Choreographer", "routine", "dance", "counts", "Jobs"),
  p("Dentist", "drill", "molars", "floss", "Jobs"),
  p("Electrician", "wires", "breaker", "voltage", "Jobs"),
  p("Florist", "bouquet", "vase", "stems", "Jobs"),
  p("Journalist", "deadline", "byline", "interview", "Jobs"),
  p("Lighthouse Keeper", "beacon", "fog", "rotation", "Jobs"),
  p("Paramedic", "siren", "stretcher", "triage", "Jobs"),
  p("Nebula", "gas", "interstellar", "glow", "Space"),
  p("Comet", "tail", "orbit", "icy", "Space"),
  p("Asteroid", "belt", "rock", "crater", "Space"),
  p("Constellation", "stars", "myth", "pattern", "Space"),
  p("Supernova", "explosion", "bright", "remnant", "Space"),
  p("Space Station", "orbit", "modules", "microgravity", "Space"),
  p("Rocket", "thrust", "staging", "payload", "Space"),
  p("Moon Landing", "apollo", "footprint", "dust", "Space"),
  p("Skeleton", "bones", "joints", "frame", "Body"),
  p("Heartbeat", "pulse", "lub", "rhythm", "Body"),
  p("Brainstem", "reflex", "vital", "bridge", "Body"),
  p("Tonsils", "throat", "immune", "removed", "Body"),
  p("Eyelash", "blink", "tiny", "curve", "Body"),
  p("Freckles", "sun", "spots", "genetic", "Body"),
  p("Taste Buds", "tongue", "sweet", "papillae", "Body"),
  p("Achilles Heel", "tendon", "weak", "myth", "Body"),
  p("Dragon", "wings", "hoard", "breath", "Fantasy"),
  p("Phoenix", "rebirth", "ashes", "flame", "Fantasy"),
  p("Unicorn", "horn", "pure", "sparkle", "Fantasy"),
  p("Griffin", "eagle", "lion", "hybrid", "Fantasy"),
  p("Mermaid", "tail", "siren", "ocean", "Fantasy"),
  p("Minotaur", "labyrinth", "bull", "horns", "Fantasy"),
  p("Kraken", "tentacles", "ship", "legend", "Fantasy"),
  p("Yeti", "snow", "footprint", "himalaya", "Fantasy"),
  p("Birthday", "candles", "cake", "wish", "Life"),
  p("Wedding", "vows", "rings", "aisle", "Life"),
  p("Graduation", "cap", "diploma", "tassel", "Life"),
  p("Jet Lag", "timezone", "fatigue", "circadian", "Life"),
  p("Déjà Vu", "familiar", "glitch", "memory", "Life"),
  p("Luck", "chance", "four", "rabbit", "Life"),
  p("Procrastination", "later", "deadline", "delay", "Life"),
  p("Curiosity", "question", "cat", "explore", "Life"),
];
